blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/brontodev/gummisaurus/discussions
    about: Discuss a feature before proposing a large implementation.
  - name: Help Or Question
    url: https://github.com/brontodev/gummisaurus/discussions
    about: Ask a Gummisaurus development or usage question.
